openapi: 3.0.0
info:
  title: Audiophile
  description: Audiophile web API
  version: 0.1.9

servers:
  - url: https://entertainment-web.onrender.com/api
    description: production server
  - url: http://localhost:5000/api
    description: local server
paths:
  /signup:
    post:
      tags:
        - user
      requestBody:
        description: add user
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        "200":
          description: user add
