openapi: 3.0.0
info:
  title: Audiophile
  description: Audiophile web API
  version: 0.1.9

servers:
  - url: https://audiophile-r04o.onrender.com/api
    description: production server
  - url: http://localhost:5000/api
    description: local server
paths:
  /signup:
    post:
      tags:
        - user
      requestBody:
        description: add user
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        "200":
          description: user add
  /login:
    post:
      tags:
        - user
      requestBody:
        description: user authorization
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: login successfully
  /signup:
    post:
      tags:
        - user
      requestBody:
        description: add user
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        "200":
          description: user add
  /products:
    get:
      tags:
        - Products
      responses:
        '200':
          description: get all products info successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string